Invoked as: ./configure 
Tclsh: /usr/bin/tclsh
Failed: cc conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccab2h0V.o: in function `main':
conftest__.c:(.text+0x5): undefined reference to `localtime_s'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void localtime_s(void);
int main(void) {
localtime_s();
return 0;
}
============
Failed: cc conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccdHKxhj.o: in function `main':
conftest__.c:(.text+0x5): undefined reference to `deflate'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void deflate(void);
int main(void) {
deflate();
return 0;
}
============
Failed: cc -c -rpath /usr/local/lib conftest__.c -o conftest__.o
cc: error: unrecognized command-line option ‘-rpath’
child process exited abnormally
============
The failed code was:
int main(void) {

return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccbME0t0.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void pthread_create(void);
int main(void) {
pthread_create();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/cc0jWJVX.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `pthread_mutexattr_init'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void pthread_mutexattr_init(void);
int main(void) {
pthread_mutexattr_init();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccw8MPKI.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `tgetent'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void tgetent(void);
int main(void) {
tgetent();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__ -lreadline
/usr/bin/ld: /tmp/ccNn9Lq6.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `tgetent'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void tgetent(void);
int main(void) {
tgetent();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__ -lncurses
/usr/bin/ld: /tmp/ccJpSi7P.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `readline'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void readline(void);
int main(void) {
readline();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
/usr/bin/ld: /tmp/ccECA0XP.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void dlopen(void);
int main(void) {
dlopen();
return 0;
}
============
Failed: cc -O2 -g conftest__.c -o conftest__
conftest__.c:1:13: warning: conflicting types for built-in function ‘ceil’; expected ‘double(double)’ [-Wbuiltin-declaration-mismatch]
    1 | extern void ceil(void);
      |             ^~~~
conftest__.c:1:1: note: ‘ceil’ is declared in header ‘<math.h>’
  +++ |+#include <math.h>
    1 | extern void ceil(void);
/usr/bin/ld: /tmp/ccb4NArA.o: in function `main':
/workspaces/cloudchatV0/sqlite-autoconf-3490100/conftest__.c:3: undefined reference to `ceil'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void ceil(void);
int main(void) {
ceil();
return 0;
}
============
